url: "sqlite3:///database.sqlite"


development:
  adapter: postgresql
  database: jet_fuel_dev
  username: <username>
  password: <password>
  host: <hostname or ip address. eg.: localhost>

#postgres://kareemgrant@localhost/jet_fuel_test

test:
  adapter: postgresql
  database: jet_fuel_test
  username: <username>
  password: <password>
  host: <hostname or ip address. eg.: localhost>